### ISSUE TITLE
DB integration

### ISSUE THREAD

**Issue by wrussian** [infiniband-radar/infiniband-radar-web#15]
Hello Carsten,
many thanks for your great application. Sorry if I overlooked something,
but is there a documentation available on how-to integrate the 
influxDB and mongoDB to the server as described in your 
presentation (https://www.spectrumscaleug.org/wp-content/uploads/2019/05/SSSD19DE-Day-2-03-Monitoring-of-InfiniBand-fabrics.pdf, page 23)? Many thanks in advance.
Cheers,
-Frank

**Comment by carstenpatzke** [comment]
Hey, when I understand you question right, you want to use an existing InfluxDB or MonogDB?
_In general the project comes with everything packed together (**including the preconfigured databases**), you just need to run `docker-compose up`._

But in the case you really want to use an existing database, you need to modify the `docker-compose.yml` and remove everything including/below `grafana:`.
<details><summary><b>Like this (<code>docker-compose.yml</code>)</b></summary>

``` yaml
version: "3"
services:
  gateway:
    build: ./gateway
    restart: unless-stopped
    depends_on:
      - api
      - grafana
      - client
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${GATEWAY_CERTS}:/etc/ssl/gateway:ro
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "5"

  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    restart: unless-stopped
    expose:
      - "80"
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "5"

  api:
    build:
      context: .
      dockerfile: Dockerfile-server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./config/:/home/node/config/:ro
    depends_on:
      - influxdb
      - mongodb
    expose:
      - "4201"
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "5"
```

</details>

Then you need to configure the `apiServer.json` in such a way that it can reach your existing database server.
<details><summary><b>Like this (<code>config/apiServer.json</code>)</b></summary>

``` json5
{
    "server": {
        "host": "0.0.0.0",
        "port": 4201
    },
    "fabrics": [
        {
            "fabricId": "fabric1",
            "name": "Fabric 1",
            "image": "<UrlToImageOrBase64Encoded>"
        },
        {
            "fabricId": "fabric2",
            "name": "Fabric 2",
            "image": "<UrlToImageOrBase64Encoded>"
        }
    ],
    "authentication": {
        "server": {
          "testToken": "localhost",
          "<TOKEN>": "<DESCRIPTION>"
        }
    },
    "influxDb": {
        "host": "some-influx-host.example.com", // <-- NEW IP OF THE DATABASE 
        "database": "infiniband_radar"
    },
    "mongoDb": {
        "host": "mongodb://some-mongo-host.example.com:27017/", // <-- NEW IP OF THE DATABASE 
        "database": "infiniband_radar"
    },
    "logLevel": "Debug"
}
```

</details>
